import type { ResolutionPathwaySummary } from '@/types/analysis'
import type { AnalysisRow, ProjectRow, ViolationRow } from '@/types/database'
import type { ReadinessResult } from '@/lib/analysis/readiness'
import { computeReadinessScore } from '@/lib/analysis/readiness'

export function parsePathways(
  raw: ViolationRow['resolution_pathways']
): ResolutionPathwaySummary[] {
  if (!raw || !Array.isArray(raw)) return []
  return raw as unknown as ResolutionPathwaySummary[]
}

export function getRecommendedPathway(
  violation: ViolationRow
): ResolutionPathwaySummary | null {
  const pathways = parsePathways(violation.resolution_pathways)
  if (pathways.length === 0) return null
  const option = violation.recommended_pathway ?? pathways[0]?.option
  return pathways.find((p) => p.option === option) ?? pathways[0] ?? null
}

export function generateApprovalPlanMarkdown(
  project: ProjectRow,
  analysis: AnalysisRow,
  violations: ViolationRow[]
): string {
  const issues = violations.filter((v) => v.severity !== 'pass')
  const readiness: ReadinessResult =
    analysis.readiness_data &&
    typeof analysis.readiness_data === 'object' &&
    !Array.isArray(analysis.readiness_data)
      ? (analysis.readiness_data as unknown as ReadinessResult)
      : computeReadinessScore(violations)

  const accepted = issues.filter((v) => v.accepted_pathway != null)
  const pending = issues.filter((v) => !v.accepted_pathway && !v.requires_manual_review)
  const manual = issues.filter((v) => v.requires_manual_review)

  const lines: string[] = [
    `# Approval Plan — ${project.name}`,
    '',
    `**FirstPass Readiness Score:** ${readiness.readiness_score}/100 (${readiness.recommendation})`,
    '',
    `| Jurisdiction | ${project.city}, ${project.state} |`,
    `| Project type | ${analysis.project_type} |`,
    `| Generated | ${new Date().toLocaleDateString()} |`,
    '',
    '## Purpose',
    '',
    'This Approval Plan is the team action list for getting this set to first-pass-ready.',
    'Each item includes the recommended resolution. Accept resolutions in the viewer, then re-run analysis.',
    '',
    `**Accepted:** ${accepted.length} · **Pending:** ${pending.length} · **Manual review:** ${manual.length}`,
    '',
  ]

  if (accepted.length > 0) {
    lines.push('## Accepted resolutions (implement on drawings)', '')
    for (const v of accepted) {
      const acceptedPath = v.accepted_pathway as ResolutionPathwaySummary | null
      lines.push(
        `### ${v.code_section} — ${v.code_title}`,
        '',
        `**Finding:** ${v.finding}`,
        '',
        `**Accepted fix:** ${acceptedPath?.action_required ?? v.recommended_action ?? v.recommendation}`,
        ''
      )
      if (v.element_location) {
        lines.push(`*Location:* ${v.element_location}`, '')
      }
    }
  }

  if (pending.length > 0) {
    lines.push('## Pending resolutions', '')
    for (const v of pending) {
      const rec = getRecommendedPathway(v)
      lines.push(
        `### ${v.code_section} — ${v.code_title}`,
        '',
        `**Finding:** ${v.finding}`,
        '',
        `**Recommended:** ${rec?.title ?? 'See recommendation'}`,
        `**Action:** ${rec?.action_required ?? v.recommended_action ?? v.recommendation}`,
        `**Design impact:** ${rec?.design_impact ?? 'n/a'} · **Cost:** ${rec?.cost_impact ?? 'n/a'}`,
        ''
      )
    }
  }

  if (manual.length > 0) {
    lines.push('## Requires manual review', '')
    for (const v of manual) {
      lines.push(`- **${v.code_section}** — ${v.finding}`)
    }
    lines.push('')
  }

  lines.push(
    '---',
    '',
    '*Approval Plan generated by FirstPass. Verify all changes with a licensed design professional before submission.*'
  )

  return lines.join('\n')
}
